version: '3.7'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        hostname: "zookeeper"
        container_name: zookeeper-v2
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - ./storage/zookeeper/data:/var/lib/zookeeper/data
            - ./storage/zookeeper/log:/var/lib/zookeeper/log
        networks:
            - default

    kafka:
        image: confluentinc/cp-kafka:latest
        hostname: "kafka"
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
          - "9092:9092"
          - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./storage/kafka:/var/lib/kafka/data

    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        hostname: "kafka-ui"
        ports:
            - "8989:8080"
        restart: always
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181